/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session/dbus/interface/org.freedesktop.systemd1.Job.xml -a ./dde-session/toolGenerate/qdbusxml2cpp/org.freedesktop.systemd1.JobAdaptor -i ./dde-session/toolGenerate/qdbusxml2cpp/org.freedesktop.systemd1.Job.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_SYSTEMD1_JOBADAPTOR_H
#define ORG_FREEDESKTOP_SYSTEMD1_JOBADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session/toolGenerate/qdbusxml2cpp/org.freedesktop.systemd1.Job.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.systemd1.Job
 */
class JobAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.systemd1.Job")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.systemd1.Job\">\n"
"    <method name=\"Cancel\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Id\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"JobType\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"State\"/>\n"
"  </interface>\n"
        "")
public:
    JobAdaptor(QObject *parent);
    virtual ~JobAdaptor();

public: // PROPERTIES
    Q_PROPERTY(uint Id READ id)
    uint id() const;

    Q_PROPERTY(QString JobType READ jobType)
    QString jobType() const;

    Q_PROPERTY(QString State READ state)
    QString state() const;

public Q_SLOTS: // METHODS
    void Cancel();
Q_SIGNALS: // SIGNALS
};

#endif
