/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session/dbus/interface/org.freedesktop.DBus.xml -a ./dde-session/toolGenerate/qdbusxml2cpp/org.freedesktop.DBusAdaptor -i ./dde-session/toolGenerate/qdbusxml2cpp/org.freedesktop.DBus.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_DBUSADAPTOR_H
#define ORG_FREEDESKTOP_DBUSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session/toolGenerate/qdbusxml2cpp/org.freedesktop.DBus.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.DBus
 */
class DBusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.DBus")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.DBus\">\n"
"    <method name=\"Hello\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"RequestName\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"u\"/>\n"
"      <arg direction=\"out\" type=\"u\"/>\n"
"    </method>\n"
"    <method name=\"ReleaseName\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"u\"/>\n"
"    </method>\n"
"    <method name=\"StartServiceByName\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"u\"/>\n"
"      <arg direction=\"out\" type=\"u\"/>\n"
"    </method>\n"
"    <method name=\"UpdateActivationEnvironment\">\n"
"      <arg direction=\"in\" type=\"a{ss}\"/>\n"
"      <annotation value=\"EnvInfoList\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"NameHasOwner\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"ListNames\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"    </method>\n"
"    <method name=\"ListActivatableNames\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"    </method>\n"
"    <method name=\"AddMatch\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"RemoveMatch\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"GetNameOwner\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"ListQueuedOwners\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"    </method>\n"
"    <method name=\"GetConnectionUnixUser\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"u\"/>\n"
"    </method>\n"
"    <method name=\"GetConnectionUnixProcessID\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"u\"/>\n"
"    </method>\n"
"    <method name=\"GetAdtAuditSessionData\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"GetConnectionSELinuxSecurityContext\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"ReloadConfig\"/>\n"
"    <method name=\"GetId\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"as\" name=\"Features\">\n"
"      <annotation value=\"const\" name=\"org.freedesktop.DBus.Property.EmitsChangedSignal\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"as\" name=\"Interfaces\">\n"
"      <annotation value=\"const\" name=\"org.freedesktop.DBus.Property.EmitsChangedSignal\"/>\n"
"    </property>\n"
"    <signal name=\"NameOwnerChanged\">\n"
"      <arg type=\"s\" name=\"name\"/>\n"
"      <arg type=\"s\" name=\"oldOwner\"/>\n"
"      <arg type=\"s\" name=\"newOwner\"/>\n"
"    </signal>\n"
"    <signal name=\"NameLost\">\n"
"      <arg type=\"s\"/>\n"
"    </signal>\n"
"    <signal name=\"NameAcquired\">\n"
"      <arg type=\"s\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    DBusAdaptor(QObject *parent);
    virtual ~DBusAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QStringList Features READ features)
    QStringList features() const;

    Q_PROPERTY(QStringList Interfaces READ interfaces)
    QStringList interfaces() const;

public Q_SLOTS: // METHODS
    void AddMatch(const QString &in0);
    QByteArray GetAdtAuditSessionData(const QString &in0);
    QByteArray GetConnectionSELinuxSecurityContext(const QString &in0);
    uint GetConnectionUnixProcessID(const QString &in0);
    uint GetConnectionUnixUser(const QString &in0);
    QString GetId();
    QString GetNameOwner(const QString &in0);
    QString Hello();
    QStringList ListActivatableNames();
    QStringList ListNames();
    QStringList ListQueuedOwners(const QString &in0);
    bool NameHasOwner(const QString &in0);
    uint ReleaseName(const QString &in0);
    void ReloadConfig();
    void RemoveMatch(const QString &in0);
    uint RequestName(const QString &in0, uint in1);
    uint StartServiceByName(const QString &in0, uint in1);
    void UpdateActivationEnvironment(EnvInfoList in0);
Q_SIGNALS: // SIGNALS
    void NameAcquired(const QString &in0);
    void NameLost(const QString &in0);
    void NameOwnerChanged(const QString &name, const QString &oldOwner, const QString &newOwner);
};

#endif
