/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session/dbus/adaptor/org.deepin.dde.Session1.xml -a ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Session1Adaptor -i ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Session1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_SESSION1ADAPTOR_H
#define ORG_DEEPIN_DDE_SESSION1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Session1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Session1
 */
class Session1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Session1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Session1\">\n"
"    <method name=\"Logout\"/>\n"
"    <method name=\"GetSessionPid\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"pid\"/>\n"
"    </method>\n"
"    <method name=\"GetSessionPath\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"sessionpath\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    Session1Adaptor(QObject *parent);
    virtual ~Session1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString GetSessionPath();
    int GetSessionPid();
    void Logout();
Q_SIGNALS: // SIGNALS
};

#endif
