/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session/dbus/adaptor/org.deepin.dde.Session1.xml -a ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Session1Adaptor -i ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Session1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Session1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Session1Adaptor
 */

Session1Adaptor::Session1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Session1Adaptor::~Session1Adaptor()
{
    // destructor
}

QString Session1Adaptor::GetSessionPath()
{
    // handle method call org.deepin.dde.Session1.GetSessionPath
    QString sessionpath;
    QMetaObject::invokeMethod(parent(), "GetSessionPath", Q_RETURN_ARG(QString, sessionpath));
    return sessionpath;
}

int Session1Adaptor::GetSessionPid()
{
    // handle method call org.deepin.dde.Session1.GetSessionPid
    int pid;
    QMetaObject::invokeMethod(parent(), "GetSessionPid", Q_RETURN_ARG(int, pid));
    return pid;
}

void Session1Adaptor::Logout()
{
    // handle method call org.deepin.dde.Session1.Logout
    QMetaObject::invokeMethod(parent(), "Logout");
}

