/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session/dbus/adaptor/org.deepin.dde.SessionManager1.xml -a ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.SessionManager1Adaptor -i ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.SessionManager1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.SessionManager1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SessionManager1Adaptor
 */

SessionManager1Adaptor::SessionManager1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SessionManager1Adaptor::~SessionManager1Adaptor()
{
    // destructor
}

QDBusObjectPath SessionManager1Adaptor::currentSessionPath() const
{
    // get the value of property CurrentSessionPath
    return qvariant_cast< QDBusObjectPath >(parent()->property("CurrentSessionPath"));
}

QString SessionManager1Adaptor::currentUid() const
{
    // get the value of property CurrentUid
    return qvariant_cast< QString >(parent()->property("CurrentUid"));
}

bool SessionManager1Adaptor::locked() const
{
    // get the value of property Locked
    return qvariant_cast< bool >(parent()->property("Locked"));
}

int SessionManager1Adaptor::stage() const
{
    // get the value of property Stage
    return qvariant_cast< int >(parent()->property("Stage"));
}

bool SessionManager1Adaptor::AllowSessionDaemonRun()
{
    // handle method call org.deepin.dde.SessionManager1.AllowSessionDaemonRun
    bool result;
    QMetaObject::invokeMethod(parent(), "AllowSessionDaemonRun", Q_RETURN_ARG(bool, result));
    return result;
}

bool SessionManager1Adaptor::CanHibernate()
{
    // handle method call org.deepin.dde.SessionManager1.CanHibernate
    bool result;
    QMetaObject::invokeMethod(parent(), "CanHibernate", Q_RETURN_ARG(bool, result));
    return result;
}

bool SessionManager1Adaptor::CanLogout()
{
    // handle method call org.deepin.dde.SessionManager1.CanLogout
    bool result;
    QMetaObject::invokeMethod(parent(), "CanLogout", Q_RETURN_ARG(bool, result));
    return result;
}

bool SessionManager1Adaptor::CanReboot()
{
    // handle method call org.deepin.dde.SessionManager1.CanReboot
    bool result;
    QMetaObject::invokeMethod(parent(), "CanReboot", Q_RETURN_ARG(bool, result));
    return result;
}

bool SessionManager1Adaptor::CanShutdown()
{
    // handle method call org.deepin.dde.SessionManager1.CanShutdown
    bool result;
    QMetaObject::invokeMethod(parent(), "CanShutdown", Q_RETURN_ARG(bool, result));
    return result;
}

bool SessionManager1Adaptor::CanSuspend()
{
    // handle method call org.deepin.dde.SessionManager1.CanSuspend
    bool result;
    QMetaObject::invokeMethod(parent(), "CanSuspend", Q_RETURN_ARG(bool, result));
    return result;
}

void SessionManager1Adaptor::ForceLogout()
{
    // handle method call org.deepin.dde.SessionManager1.ForceLogout
    QMetaObject::invokeMethod(parent(), "ForceLogout");
}

void SessionManager1Adaptor::ForceReboot()
{
    // handle method call org.deepin.dde.SessionManager1.ForceReboot
    QMetaObject::invokeMethod(parent(), "ForceReboot");
}

void SessionManager1Adaptor::ForceShutdown()
{
    // handle method call org.deepin.dde.SessionManager1.ForceShutdown
    QMetaObject::invokeMethod(parent(), "ForceShutdown");
}

QList<QDBusObjectPath> SessionManager1Adaptor::GetInhibitors()
{
    // handle method call org.deepin.dde.SessionManager1.GetInhibitors
    QList<QDBusObjectPath> Inhibitors;
    QMetaObject::invokeMethod(parent(), "GetInhibitors", Q_RETURN_ARG(QList<QDBusObjectPath>, Inhibitors));
    return Inhibitors;
}

uint SessionManager1Adaptor::Inhibit(const QString &appId, uint toplevelXid, const QString &reason, uint flags)
{
    // handle method call org.deepin.dde.SessionManager1.Inhibit
    uint inhibitCookie;
    QMetaObject::invokeMethod(parent(), "Inhibit", Q_RETURN_ARG(uint, inhibitCookie), Q_ARG(QString, appId), Q_ARG(uint, toplevelXid), Q_ARG(QString, reason), Q_ARG(uint, flags));
    return inhibitCookie;
}

bool SessionManager1Adaptor::IsInhibited(uint flags)
{
    // handle method call org.deepin.dde.SessionManager1.IsInhibited
    bool ret;
    QMetaObject::invokeMethod(parent(), "IsInhibited", Q_RETURN_ARG(bool, ret), Q_ARG(uint, flags));
    return ret;
}

void SessionManager1Adaptor::Logout()
{
    // handle method call org.deepin.dde.SessionManager1.Logout
    QMetaObject::invokeMethod(parent(), "Logout");
}

void SessionManager1Adaptor::PowerOffChoose()
{
    // handle method call org.deepin.dde.SessionManager1.PowerOffChoose
    QMetaObject::invokeMethod(parent(), "PowerOffChoose");
}

void SessionManager1Adaptor::Reboot()
{
    // handle method call org.deepin.dde.SessionManager1.Reboot
    QMetaObject::invokeMethod(parent(), "Reboot");
}

bool SessionManager1Adaptor::Register(const QString &id)
{
    // handle method call org.deepin.dde.SessionManager1.Register
    bool result;
    QMetaObject::invokeMethod(parent(), "Register", Q_RETURN_ARG(bool, result), Q_ARG(QString, id));
    return result;
}

void SessionManager1Adaptor::RequestHibernate()
{
    // handle method call org.deepin.dde.SessionManager1.RequestHibernate
    QMetaObject::invokeMethod(parent(), "RequestHibernate");
}

void SessionManager1Adaptor::RequestLock()
{
    // handle method call org.deepin.dde.SessionManager1.RequestLock
    QMetaObject::invokeMethod(parent(), "RequestLock");
}

void SessionManager1Adaptor::RequestLogout()
{
    // handle method call org.deepin.dde.SessionManager1.RequestLogout
    QMetaObject::invokeMethod(parent(), "RequestLogout");
}

void SessionManager1Adaptor::RequestReboot()
{
    // handle method call org.deepin.dde.SessionManager1.RequestReboot
    QMetaObject::invokeMethod(parent(), "RequestReboot");
}

void SessionManager1Adaptor::RequestShutdown()
{
    // handle method call org.deepin.dde.SessionManager1.RequestShutdown
    QMetaObject::invokeMethod(parent(), "RequestShutdown");
}

void SessionManager1Adaptor::RequestSuspend()
{
    // handle method call org.deepin.dde.SessionManager1.RequestSuspend
    QMetaObject::invokeMethod(parent(), "RequestSuspend");
}

void SessionManager1Adaptor::SetLocked(bool value)
{
    // handle method call org.deepin.dde.SessionManager1.SetLocked
    QMetaObject::invokeMethod(parent(), "SetLocked", Q_ARG(bool, value));
}

void SessionManager1Adaptor::Shutdown()
{
    // handle method call org.deepin.dde.SessionManager1.Shutdown
    QMetaObject::invokeMethod(parent(), "Shutdown");
}

void SessionManager1Adaptor::ToggleDebug()
{
    // handle method call org.deepin.dde.SessionManager1.ToggleDebug
    QMetaObject::invokeMethod(parent(), "ToggleDebug");
}

void SessionManager1Adaptor::Uninhibit(uint inhibitCookie)
{
    // handle method call org.deepin.dde.SessionManager1.Uninhibit
    QMetaObject::invokeMethod(parent(), "Uninhibit", Q_ARG(uint, inhibitCookie));
}

