/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session/dbus/interface/org.deepin.dde.Bluetooth1.xml -a ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Bluetooth1Adaptor -i ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Bluetooth1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Bluetooth1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Bluetooth1Adaptor
 */

Bluetooth1Adaptor::Bluetooth1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Bluetooth1Adaptor::~Bluetooth1Adaptor()
{
    // destructor
}

bool Bluetooth1Adaptor::canSendFile() const
{
    // get the value of property CanSendFile
    return qvariant_cast< bool >(parent()->property("CanSendFile"));
}

uint Bluetooth1Adaptor::state() const
{
    // get the value of property State
    return qvariant_cast< uint >(parent()->property("State"));
}

void Bluetooth1Adaptor::ClearUnpairedDevice()
{
    // handle method call org.deepin.dde.Bluetooth1.ClearUnpairedDevice
    QMetaObject::invokeMethod(parent(), "ClearUnpairedDevice");
}

void Bluetooth1Adaptor::ConnectDevice(const QDBusObjectPath &devPath, const QDBusObjectPath &adapterPath)
{
    // handle method call org.deepin.dde.Bluetooth1.ConnectDevice
    QMetaObject::invokeMethod(parent(), "ConnectDevice", Q_ARG(QDBusObjectPath, devPath), Q_ARG(QDBusObjectPath, adapterPath));
}

QString Bluetooth1Adaptor::DebugInfo()
{
    // handle method call org.deepin.dde.Bluetooth1.DebugInfo
    QString info;
    QMetaObject::invokeMethod(parent(), "DebugInfo", Q_RETURN_ARG(QString, info));
    return info;
}

void Bluetooth1Adaptor::DisconnectAudioDevices()
{
    // handle method call org.deepin.dde.Bluetooth1.DisconnectAudioDevices
    QMetaObject::invokeMethod(parent(), "DisconnectAudioDevices");
}

void Bluetooth1Adaptor::DisconnectDevice(const QDBusObjectPath &devPath)
{
    // handle method call org.deepin.dde.Bluetooth1.DisconnectDevice
    QMetaObject::invokeMethod(parent(), "DisconnectDevice", Q_ARG(QDBusObjectPath, devPath));
}

QString Bluetooth1Adaptor::GetAdapters()
{
    // handle method call org.deepin.dde.Bluetooth1.GetAdapters
    QString adaptersJSON;
    QMetaObject::invokeMethod(parent(), "GetAdapters", Q_RETURN_ARG(QString, adaptersJSON));
    return adaptersJSON;
}

QString Bluetooth1Adaptor::GetDevices(const QDBusObjectPath &adapterPath)
{
    // handle method call org.deepin.dde.Bluetooth1.GetDevices
    QString devicesJSON;
    QMetaObject::invokeMethod(parent(), "GetDevices", Q_RETURN_ARG(QString, devicesJSON), Q_ARG(QDBusObjectPath, adapterPath));
    return devicesJSON;
}

void Bluetooth1Adaptor::RegisterAgent(const QDBusObjectPath &agentPath)
{
    // handle method call org.deepin.dde.Bluetooth1.RegisterAgent
    QMetaObject::invokeMethod(parent(), "RegisterAgent", Q_ARG(QDBusObjectPath, agentPath));
}

void Bluetooth1Adaptor::RemoveDevice(const QDBusObjectPath &adapterPath, const QDBusObjectPath &devPath)
{
    // handle method call org.deepin.dde.Bluetooth1.RemoveDevice
    QMetaObject::invokeMethod(parent(), "RemoveDevice", Q_ARG(QDBusObjectPath, adapterPath), Q_ARG(QDBusObjectPath, devPath));
}

void Bluetooth1Adaptor::RequestDiscovery(const QDBusObjectPath &adapterPath)
{
    // handle method call org.deepin.dde.Bluetooth1.RequestDiscovery
    QMetaObject::invokeMethod(parent(), "RequestDiscovery", Q_ARG(QDBusObjectPath, adapterPath));
}

void Bluetooth1Adaptor::SetAdapterAlias(const QDBusObjectPath &adapterPath, const QString &alias)
{
    // handle method call org.deepin.dde.Bluetooth1.SetAdapterAlias
    QMetaObject::invokeMethod(parent(), "SetAdapterAlias", Q_ARG(QDBusObjectPath, adapterPath), Q_ARG(QString, alias));
}

void Bluetooth1Adaptor::SetAdapterDiscoverable(const QDBusObjectPath &adapterPath, bool discoverable)
{
    // handle method call org.deepin.dde.Bluetooth1.SetAdapterDiscoverable
    QMetaObject::invokeMethod(parent(), "SetAdapterDiscoverable", Q_ARG(QDBusObjectPath, adapterPath), Q_ARG(bool, discoverable));
}

void Bluetooth1Adaptor::SetAdapterDiscoverableTimeout(const QDBusObjectPath &adapterPath, uint discoverableTimeout)
{
    // handle method call org.deepin.dde.Bluetooth1.SetAdapterDiscoverableTimeout
    QMetaObject::invokeMethod(parent(), "SetAdapterDiscoverableTimeout", Q_ARG(QDBusObjectPath, adapterPath), Q_ARG(uint, discoverableTimeout));
}

void Bluetooth1Adaptor::SetAdapterDiscovering(const QDBusObjectPath &adapterPath, bool discovering)
{
    // handle method call org.deepin.dde.Bluetooth1.SetAdapterDiscovering
    QMetaObject::invokeMethod(parent(), "SetAdapterDiscovering", Q_ARG(QDBusObjectPath, adapterPath), Q_ARG(bool, discovering));
}

void Bluetooth1Adaptor::SetAdapterPowered(const QDBusObjectPath &adapterPath, bool powered)
{
    // handle method call org.deepin.dde.Bluetooth1.SetAdapterPowered
    QMetaObject::invokeMethod(parent(), "SetAdapterPowered", Q_ARG(QDBusObjectPath, adapterPath), Q_ARG(bool, powered));
}

void Bluetooth1Adaptor::SetDeviceAlias(const QDBusObjectPath &device, const QString &alias)
{
    // handle method call org.deepin.dde.Bluetooth1.SetDeviceAlias
    QMetaObject::invokeMethod(parent(), "SetDeviceAlias", Q_ARG(QDBusObjectPath, device), Q_ARG(QString, alias));
}

void Bluetooth1Adaptor::SetDeviceTrusted(const QDBusObjectPath &device, bool trusted)
{
    // handle method call org.deepin.dde.Bluetooth1.SetDeviceTrusted
    QMetaObject::invokeMethod(parent(), "SetDeviceTrusted", Q_ARG(QDBusObjectPath, device), Q_ARG(bool, trusted));
}

void Bluetooth1Adaptor::UnregisterAgent(const QDBusObjectPath &agentPath)
{
    // handle method call org.deepin.dde.Bluetooth1.UnregisterAgent
    QMetaObject::invokeMethod(parent(), "UnregisterAgent", Q_ARG(QDBusObjectPath, agentPath));
}

