/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session/dbus/interface/org.deepin.dde.Daemon1.xml -a ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Daemon1Adaptor -i ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Daemon1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Daemon1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Daemon1Adaptor
 */

Daemon1Adaptor::Daemon1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Daemon1Adaptor::~Daemon1Adaptor()
{
    // destructor
}

void Daemon1Adaptor::CallTrace(uint times, uint seconds)
{
    // handle method call org.deepin.dde.Daemon1.CallTrace
    QMetaObject::invokeMethod(parent(), "CallTrace", Q_ARG(uint, times), Q_ARG(uint, seconds));
}

void Daemon1Adaptor::StartPart2()
{
    // handle method call org.deepin.dde.Daemon1.StartPart2
    QMetaObject::invokeMethod(parent(), "StartPart2");
}

