/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session/dbus/adaptor/org.deepin.dde.Inhibitor1.xml -a ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Inhibitor1Adaptor -i ./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Inhibitor1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_INHIBITOR1ADAPTOR_H
#define ORG_DEEPIN_DDE_INHIBITOR1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session/toolGenerate/qdbusxml2cpp/org.deepin.dde.Inhibitor1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Inhibitor1
 */
class Inhibitor1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Inhibitor1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Inhibitor1\">\n"
"    <method name=\"GetAppId\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"GetClientId\">\n"
"      <arg direction=\"out\" type=\"o\"/>\n"
"    </method>\n"
"    <method name=\"GetFlags\">\n"
"      <arg direction=\"out\" type=\"u\"/>\n"
"    </method>\n"
"    <method name=\"GetReason\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"GetToplevelXid\">\n"
"      <arg direction=\"out\" type=\"u\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    Inhibitor1Adaptor(QObject *parent);
    virtual ~Inhibitor1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString GetAppId();
    QDBusObjectPath GetClientId();
    uint GetFlags();
    QString GetReason();
    uint GetToplevelXid();
Q_SIGNALS: // SIGNALS
};

#endif
