/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session/dbus/interface/org.freedesktop.systemd1.Job.xml -a ./dde-session/toolGenerate/qdbusxml2cpp/org.freedesktop.systemd1.JobAdaptor -i ./dde-session/toolGenerate/qdbusxml2cpp/org.freedesktop.systemd1.Job.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session/toolGenerate/qdbusxml2cpp/org.freedesktop.systemd1.JobAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class JobAdaptor
 */

JobAdaptor::JobAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

JobAdaptor::~JobAdaptor()
{
    // destructor
}

uint JobAdaptor::id() const
{
    // get the value of property Id
    return qvariant_cast< uint >(parent()->property("Id"));
}

QString JobAdaptor::jobType() const
{
    // get the value of property JobType
    return qvariant_cast< QString >(parent()->property("JobType"));
}

QString JobAdaptor::state() const
{
    // get the value of property State
    return qvariant_cast< QString >(parent()->property("State"));
}

void JobAdaptor::Cancel()
{
    // handle method call org.freedesktop.systemd1.Job.Cancel
    QMetaObject::invokeMethod(parent(), "Cancel");
}

